services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-https://apiprodesign.pro-invest.pe}
        VITE_API_BASE_URL_CALCULATE: ${VITE_API_BASE_URL_CALCULATE:-https://apiprodesign.pro-invest.pe}
        VITE_URL_PROINVIERTE: ${VITE_URL_PROINVIERTE:-https://apiproinvierte.pro-invest.pe}
        VITE_URL_PROBUDGETS_PORTAL: ${VITE_URL_PROBUDGETS_PORTAL:-https://probudget.pro-invest.pe/admin/budget/list}
    container_name: prodesign-react
    ports:
      - "5199:80"
    restart: always
    networks:
      - prodesign_network

networks:
  prodesign_network:
    external: true